"""add refresh tokens

Revision ID: 0680db0b4d80
Revises: 10825745eb6b
Create Date: 2025-11-01 17:36:30.651075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0680db0b4d80'
down_revision = '10825745eb6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False, comment='自增ID'),
    sa.Column('jti', sa.String(length=36), nullable=False, comment='当前刷新令牌 JTI(唯一)'),
    sa.Column('parent_jti', sa.String(length=36), nullable=True, comment='父刷新令牌 JTI，用于家族/链追踪'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='用户ID'),
    sa.Column('issued_at', sa.DateTime(), nullable=False, comment='签发时间'),
    sa.Column('expires_at', sa.DateTime(), nullable=False, comment='过期时间'),
    sa.Column('used_at', sa.DateTime(), nullable=True, comment='已使用时间（轮换时置位）'),
    sa.Column('revoked', sa.Boolean(), server_default='0', nullable=False, comment='是否撤销'),
    sa.Column('revoked_reason', sa.String(length=200), nullable=True, comment='撤销原因'),
    sa.Column('device_id', sa.String(length=100), nullable=True, comment='设备ID'),
    sa.Column('ip', sa.String(length=64), nullable=True, comment='IP 地址'),
    sa.Column('user_agent', sa.String(length=255), nullable=True, comment='User-Agent'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('refresh_tokens_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('refresh_tokens_pkey')),
    sa.UniqueConstraint('jti', name=op.f('refresh_tokens_jti_key'))
    )
    op.create_index('refresh_tokens_expires_at_idx', 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index('refresh_tokens_parent_jti_idx', 'refresh_tokens', ['parent_jti'], unique=False)
    op.create_index('refresh_tokens_user_id_idx', 'refresh_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('refresh_tokens_user_id_idx', table_name='refresh_tokens')
    op.drop_index('refresh_tokens_parent_jti_idx', table_name='refresh_tokens')
    op.drop_index('refresh_tokens_expires_at_idx', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
