"""delete_user_failed_login

Revision ID: 5df1b2a8056b
Revises: 0680db0b4d80
Create Date: 2025-12-11 11:24:10.311648

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5df1b2a8056b'
down_revision = '0680db0b4d80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'failed_login_attempts')
    op.drop_column('users', 'lock_until')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('lock_until', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='账号锁定到期时间'))
    op.add_column('users', sa.Column('failed_login_attempts', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False, comment='30分钟内连续失败次数'))
    # ### end Alembic commands ###
