"""add_users

Revision ID: 10825745eb6b
Revises: 50920efc2fad
Create Date: 2025-11-01 12:34:57.506121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10825745eb6b'
down_revision = '50920efc2fad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False, comment='用户ID(UUID)'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名(唯一)'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='密码哈希'),
    sa.Column('role', sa.String(length=10), server_default='user', nullable=False, comment='角色：admin/user'),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False, comment='是否启用'),
    sa.Column('token_version', sa.Integer(), server_default='1', nullable=False, comment='令牌版本'),
    sa.Column('failed_login_attempts', sa.Integer(), server_default='0', nullable=False, comment='30分钟内连续失败次数'),
    sa.Column('lock_until', sa.DateTime(), nullable=True, comment='账号锁定到期时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('username', name=op.f('users_username_key'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
