"""init_schema

Revision ID: 50920efc2fad
Revises:
Create Date: 2025-09-27 17:29:41.477084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50920efc2fad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False, comment='学生ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='学生姓名'),
    sa.Column('gender', sa.String(length=10), nullable=False, comment='性别：male/female'),
    sa.Column('age', sa.Integer(), nullable=True, comment='年龄'),
    sa.Column('student_id', sa.String(length=50), nullable=False, comment='学号'),
    sa.PrimaryKeyConstraint('id', name=op.f('students_pkey'))
    )
    op.create_index(op.f('students_id_idx'), 'students', ['id'], unique=False)
    op.create_index(op.f('students_student_id_idx'), 'students', ['student_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('students_student_id_idx'), table_name='students')
    op.drop_index(op.f('students_id_idx'), table_name='students')
    op.drop_table('students')
    # ### end Alembic commands ###
