name: Deploy

on:
  workflow_run:
    workflows: ["Build and Push"]
    branches:
      - "main"
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.SERVER_SSH_HOST }}
          username: ${{ secrets.SERVER_SSH_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: ${{ vars.SERVER_SSH_SCRIPT || 'cd services/fastapi-nextjs-template/docker && ./fastapi-nextjs-service.sh start && docker image prune -af' }}
