name: Style Checks

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  python-style:
    name: API Ruff Style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Check changed files
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          files: |
            api/**
            .github/workflows/style.yml

      - name: Setup Python
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Ruff
        if: steps.changed-files.outputs.any_changed == 'true'
        run: pip install ruff==0.12.8

      - name: Ruff check
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          ruff --version
          ruff check ./api
          ruff format --check ./api

      - name: Lint hints
        if: failure()
        run: |
          echo '请运行: ruff check --fix ./api && ruff format ./api 来自动修复可修复的问题。'
          echo '若仍有未修复的问题，请根据 Ruff 的输出逐项手动修复剩余问题。'


  web-eslint:
    name: Web ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Check changed files
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          files: |
            web/**
            .github/workflows/style.yml

      - name: Setup Node.js
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: web/package-lock.json

      - name: Install dependencies (npm)
        if: steps.changed-files.outputs.any_changed == 'true'
        working-directory: web
        run: npm ci

      - name: Run ESLint
        if: steps.changed-files.outputs.any_changed == 'true'
        working-directory: web
        run: npm run lint -- .

      - name: Lint hints
        if: failure()
        run: |
          echo '请在 web 目录运行: npm run lint -- --fix . 来自动修复可修复的问题。'
          echo '若仍有未修复的问题，请根据 ESLint 输出逐项手动修复剩余问题。'
